on: push
name: Main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: docker://basaltinc/docker-node-php-base:latest
      with:
        entrypoint: sh
        args: -c "npm ci && composer install"
    - name: build
      run: npm run build
    - name: test
      run: npm test
    - name: eslint
      uses: hallee/eslint-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: semantic release
      uses: docker://basaltinc/docker-node-php-base:latest
      if: github.ref == 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        entrypoint: npx
        args: semantic-release
